name: Node.js deploy		

on:
 push:		
   branches: [ master ]		

jobs:		
 build:		
    runs-on: ubuntu-latest		

    strategy:		
     matrix:		
       node-version: [10.x]		

    steps:
     - uses: actions/checkout@v2		
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ secrets.AWS_REGION }}		
     - name: Use Node.js ${{ matrix.node-version }}		
       uses: actions/setup-node@v1		
       with:		
         node-version: ${{ matrix.node-version }}		
     - run: npm install		
     - run: npm run build --if-present		
     - name: Build and push backend image
       uses: docker/build-push-action@v1.1.0
       with:
         username: ${{ secrets.DOCKER_USER }}
         password: ${{ secrets.DOCKER_PASS }}
         dockerfile: '{path}/DockerFile'
         repository: ${{ secrets.DOCKER_USER }}/${{ secrets.BACKEND_NAME }}
         tags: latest
