name: Node.js deploy		

on:
 push:		
   branches: [ master ]		

jobs:		
 build:		
    runs-on: ubuntu-latest		

    strategy:		
     matrix:		
       node-version: [10.x]		

    steps:
     - uses: actions/checkout@v2		
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ secrets.AWS_REGION }}		
     - name: Use Node.js ${{ matrix.node-version }}		
       uses: actions/setup-node@v1		
       with:		
         node-version: ${{ matrix.node-version }}		
     - run: npm install		
     - run: npm run build --if-present		
     - name: Deploy to Server		
       uses: easingthemes/ssh-deploy@v2.1.1		
       env:
        		 EC2_IP: $(aws ec2 describe-addresses --query "Addresses[*].PublicIp" --output text)
           SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}		
           ARGS: "-rltgoDzvO --delete"		
           SOURCE: "/"		
           REMOTE_HOST: ${{ env.EC2_IP }}
           REMOTE_USER: ${{ secrets.REMOTE_USER }}		
           TARGET: /home/${{ secrets.REMOTE_USER }}/pixelistic_app
